### ISSUE TITLE
>ban and >kick commands

### ISSUE THREAD

**Issue by Yeffian** [BotMyst/BotMystRevival#15]
Let's be honest, all bots need banning and kicking commands

**Comment by ibra** [comment]
BotMyst was originally meant to be a general-purpose utility bot, not meant for moderation (doesn't even have a DB connection). 

However, I've heard quite a few people asking me to just make it an all-purpose bot.

 I'd love to hear thoughts on this though ^^.

**Comment by Yeffian** [comment]
I think you should make it a general-purpose bot with moderation built-in, since it already has a few moderation commands (albeit soft moderation)

**Comment by ibra** [comment]
alright

**Comment by ibra** [comment]
closed in favour of #16 and #17
